@extends('layouts.app')
@php $pageTitle = 'Add Settlement'; @endphp

@section('content')
<div x-data="{ trips: @js($tripOptions), selectedId: '', selectedTrip: null, actualCash: 0, refresh() { this.selectedTrip = this.trips.find(trip => String(trip.id) === String(this.selectedId)) ?? null; this.actualCash = this.selectedTrip?.collections ?? 0; }, money(value) { return 'PKR ' + Number(value ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2 }); } }">
    <div class="mb-5 flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('settlements.index') }}" class="text-sm font-bold text-blue-600">&larr; Back to Settlements</a><h2 class="mt-2 text-2xl font-black text-slate-900">Add Settlement</h2><p class="mt-1 text-sm text-slate-500">Select an existing Trip ID to prepare its end-of-day clearing sheet.</p></div><span class="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">Auto-filled from Trip</span></div>
    <form class="space-y-5" @submit.prevent>
        <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">1. Select Existing Trip</h3><p class="mt-1 text-sm text-slate-500">Trip and expense information is fetched using the same Trip ID.</p><div class="mt-5 max-w-xl"><label class="mb-1 block text-xs font-bold text-slate-600">Trip / Route ID *</label><select x-model="selectedId" @change="refresh()" required class="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select a trip</option><template x-for="trip in trips" :key="trip.id"><option :value="trip.id" x-text="trip.id + ' · ' + trip.driver + ' · ' + trip.market"></option></template></select></div></section>
        <template x-if="selectedTrip"><div class="space-y-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">2. Trip Information Fetched</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-4"><template x-for="field in [['Date',selectedTrip.date],['Driver / Deliveryman',selectedTrip.driver],['Vehicle / Van',selectedTrip.vehicle],['Market / Route',selectedTrip.market],['Distributor',selectedTrip.distributor],['Net Sales Value',money(selectedTrip.net_sales)],['Market Credit / Udhaar',money(selectedTrip.credit)],['Trip Expenses',money(selectedTrip.expenses)]]" :key="field[0]"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400" x-text="field[0]"></p><p class="mt-1 font-bold text-slate-800" x-text="field[1]"></p></div></template></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">3. Settlement Cash Reconciliation</h3><div class="mt-5 grid grid-cols-1 gap-5 md:grid-cols-3"><div><label class="mb-1 block text-xs font-bold text-slate-600">Expected Cash from Trip</label><input readonly :value="money(selectedTrip.net_sales - selectedTrip.credit - selectedTrip.expenses)" class="w-full rounded-lg border border-slate-300 bg-slate-50 px-3 py-2.5 text-sm font-bold"></div><div><label class="mb-1 block text-xs font-bold text-slate-600">Actual Cash Submitted *</label><input type="number" min="0" step="0.01" x-model.number="actualCash" required class="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"></div><div><label class="mb-1 block text-xs font-bold text-slate-600">Shortage / Excess</label><input readonly :value="money((selectedTrip.net_sales - selectedTrip.credit - selectedTrip.expenses) - actualCash)" class="w-full rounded-lg border border-slate-300 bg-slate-50 px-3 py-2.5 text-sm font-bold text-red-600"></div></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">4. Final Settlement Details</h3><div class="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2"><div><label class="mb-1 block text-xs font-bold text-slate-600">Shortage Action *</label><select required class="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>Charge to Salesman Ledger</option><option>Recover from Salary</option><option>Approved Waiver</option></select></div><div><label class="mb-1 block text-xs font-bold text-slate-600">Settled By *</label><select required class="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>Manager</option><option>Admin</option></select></div></div></section>
            <div class="flex justify-end gap-2"><a href="{{ route('settlements.index') }}" class="rounded-lg bg-slate-100 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</a><button type="submit" class="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-bold text-white">Save Settlement</button></div>
        </div></template>
        <div x-show="!selectedTrip" class="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-12 text-center text-sm text-slate-500">Select a Trip ID above to fetch its trip and expense data.</div>
    </form>
</div>
@endsection
