@extends('layouts.app')
@php $pageTitle = 'Daily Driver & Trip Settlements'; @endphp

@section('content')
<div x-data="{ open: false, selected: null, showSettlement(item) { window.location.href = '/settlements/' + item.id; }, close() { this.open = false; } }" x-effect="document.body.style.overflow = open ? 'hidden' : ''" @keydown.escape.window="close()">
    <div class="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-600">End-of-Day Reconciliation</p><h2 class="mt-1 text-2xl font-black text-slate-900">Daily Driver &amp; Trip Settlements</h2><p class="mt-1 text-sm text-slate-500">End-of-Day Reconciliation for Deliverymen, Stock, Cash Collections, and Shortages</p></div><a href="{{ route('settlements.create') }}" class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">+ Add Settlement</a></div>
    <div class="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Settlements Today',$totalSettlements,'#1d4ed8','#eff6ff'],['Total Net Cash Collected',$totalCash,'#15803d','#f0fdf4'],['Total Market Credit Issued (Udhaar)',$totalCredit,'#b45309','#fffbeb'],['Total Pending Shortages Today',$totalShortage,'#b91c1c','#fff1f2']] as [$label,$value,$color,$background])<div class="min-h-32 rounded-xl border border-slate-200 p-5 shadow-sm" style="background:{{ $background }}"><p class="text-xs font-bold uppercase tracking-wide" style="color:{{ $color }};opacity:.75">{{ $label }}</p><p class="mt-2 text-2xl font-black" style="color:{{ $color }}">{{ pkr($value) }}</p></div>@endforeach</div>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-6 py-5"><h3 class="text-lg font-black text-slate-900">Settlements Main Table</h3><p class="mt-1 text-xs text-slate-500">Trip clearing, stock reconciliation, and cash drawer handover.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[90rem] text-sm"><thead><tr class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-400"><th class="px-5 py-3">Settlement ID / Slip No</th><th class="px-5 py-3">Date</th><th class="px-5 py-3">Trip / Route ID</th><th class="px-5 py-3">Deliveryman / Driver Name</th><th class="px-5 py-3">Market / Area</th><th class="px-5 py-3">Distributor Name</th><th class="px-5 py-3 text-right">Net Sales Value (PKR)</th><th class="px-5 py-3 text-right">Expected Cash (PKR)</th><th class="px-5 py-3 text-right">Actual Submitted Cash (PKR)</th><th class="px-5 py-3 text-right">Shortage / Excess (PKR)</th><th class="px-5 py-3">Settlement Status</th><th class="px-5 py-3">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($settlements as $settlement)<tr class="hover:bg-slate-50"><td class="px-5 py-4 font-mono text-xs font-black text-blue-700">{{ $settlement['settlement_ref'] }}</td><td class="px-5 py-4 whitespace-nowrap">{{ $settlement['date'] }}</td><td class="px-5 py-4 font-mono text-xs">{{ $settlement['trip_display'] }}</td><td class="px-5 py-4 font-semibold">{{ $settlement['deliveryman'] }}</td><td class="px-5 py-4">{{ $settlement['market'] }}</td><td class="px-5 py-4">{{ $settlement['distributor'] }}</td><td class="px-5 py-4 text-right font-bold">{{ pkr($settlement['net_sales']) }}</td><td class="px-5 py-4 text-right">{{ pkr($settlement['expected_cash']) }}</td><td class="px-5 py-4 text-right font-bold text-green-700">{{ pkr($settlement['actual_cash']) }}</td><td class="px-5 py-4 text-right font-bold {{ $settlement['shortage'] > 0 ? 'text-red-600' : 'text-slate-400' }}">{{ $settlement['shortage'] > 0 ? pkr($settlement['shortage']) : 'PKR 0.00' }}</td><td class="px-5 py-4"><x-status-badge :status="$settlement['status']" /></td><td class="px-5 py-4"><button type="button" @click="showSettlement({{ json_encode($settlement) }})" class="whitespace-nowrap rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700 hover:bg-blue-100">View Settlement Details</button></td></tr>@endforeach</tbody></table></div></section>

    @if(false)<div x-show="open"></div>@endif
</div>
@endsection
