@extends('layouts.app')
@php $pageTitle = $record['settlement_ref']; @endphp

@section('content')
<div class="mb-5 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('settlements.index') }}" class="text-sm font-bold text-blue-600">&larr; Back to Settlements</a><h2 class="mt-2 text-2xl font-black text-slate-900">{{ $record['settlement_ref'] }}</h2><p class="mt-1 text-sm text-slate-500">Trip clearing and cash reconciliation sheet</p></div><x-status-badge :status="$record['status']" /></div>
<div class="space-y-5">
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Part A: Driver &amp; Route Summary</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-5">@foreach([['Settlement Reference',$record['settlement_ref']],['Driver Name',$record['deliveryman']],['Vehicle / Van No',$record['vehicle']],['Route / Market',$record['market']],['Distributor',$record['distributor']]] as [$label,$value])<div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-1 font-bold text-slate-800">{{ $value }}</p></div>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Part B: Stock Value Reconciliation</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-4">@foreach([['Gross Stock Loaded (PKR)',$record['loaded']],['Unsold Returned Stock (PKR)',$record['returned']],['Damaged / Expired Returns (PKR)',$record['damaged']],['Total Gross Sales Value (PKR)',$record['loaded'] - $record['returned']]] as [$label,$value])<div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-1 text-lg font-black text-slate-800">{{ pkr($value) }}</p></div>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Part C: Payment &amp; Collections Breakdown</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-5">@foreach([['Trade Discounts / Schemes (PKR)',$record['discounts']],['Market Credit / Udhaar (PKR)',$record['credit']],['Cheque Collections (PKR)',$record['cheques']],['Online Transfers (PKR)',$record['transfers']],['Expected Net Cash from Driver (PKR)',$record['expected_cash']]] as [$label,$value])<div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-1 font-black text-slate-800">{{ pkr($value) }}</p></div>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-slate-50 p-6"><h3 class="text-lg font-black text-slate-900">Part D: Cash Drawer Handover &amp; Shortage Result</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-5"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Actual Cash Handed Over</p><p class="mt-1 font-black text-slate-800">{{ pkr($record['actual_cash']) }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Driver Cash Shortage</p><p class="mt-1 font-black text-red-600">{{ pkr($record['shortage']) }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Driver Cash Excess</p><p class="mt-1 font-black text-green-600">{{ pkr($record['excess']) }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Shortage Action</p><p class="mt-1 font-bold text-slate-800">{{ $record['action'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Settled By</p><p class="mt-1 font-bold text-slate-800">{{ $record['settled_by'] }}</p></div></div></section>
</div>
@endsection
