@extends('layouts.app')
@php $pageTitle = 'Create Ledger Entry'; @endphp

@section('content')
<div class="mb-5"><a href="{{ route('ledgers.index') }}" class="text-sm font-bold text-gray-700">&larr; Back to Ledgers</a><h2 class="mt-2 text-2xl font-black text-slate-900">{{ isset($editId) ? 'Edit Ledger Entry' : 'Create Ledger Entry' }}</h2><p class="mt-1 text-sm text-slate-500">Record a supplier payable or driver receivable entry.</p></div>
<form x-data='{ entry: @json($entry ?? []) }' method="POST" action="{{ isset($editId) ? route('ledgers.update', $editId) : route('ledgers.store') }}" enctype="multipart/form-data" class="space-y-5">@csrf @isset($editId) @method('PUT') @endisset
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Section 1: Ledger Type &amp; Entity Selection</h3><div class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="ledger-label">Ledger Group *</label><select name="ledger_group" required class="ledger-field" x-init="$el.value = entry.ledger_group ?? $el.options[0].value"><option value="Supplier">Supplier</option><option value="Driver">Driver</option></select></div><div><label class="ledger-label">Entity Name *</label><select name="entity_name" required class="ledger-field" x-init="$el.value = entry.entity_name ?? $el.options[0].value"><option>EBM - English Biscuit Manufacturers</option><option>CFL - Coronet Foods Limited</option>@foreach($drivers as $driver)<option>{{ $driver }}</option>@endforeach</select></div><div><label class="ledger-label">Entry Date *</label><input type="date" name="entry_date" required class="ledger-field" :value="entry.entry_date?.slice(0, 10) ?? ''"></div><div><label class="ledger-label">Voucher / Reference No. *</label><input name="voucher_reference" required placeholder="EBM-INV-8892" class="ledger-field" :value="entry.voucher_reference ?? ''"></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Section 2: Transaction &amp; Financials</h3><div class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="ledger-label">Transaction Category *</label><select name="transaction_category" required class="ledger-field" x-init="$el.value = entry.transaction_category ?? $el.options[0].value"><option>Primary Stock Lifting</option><option>Supplier Payment</option><option>Return Claim</option><option>Driver Cash Shortage</option><option>Driver Salary Recovery</option></select></div><div><label class="ledger-label">Entry Type *</label><div class="flex gap-2"><label class="flex flex-1 items-center gap-2 rounded-lg border border-gray-300 bg-gray-100 px-4 py-3 text-sm font-bold text-gray-700"><input type="radio" name="entry_type" value="Debit" :checked="(entry.entry_type ?? 'Debit') === 'Debit'"> Debit [Dr]</label><label class="flex flex-1 items-center gap-2 rounded-lg border border-gray-300 bg-gray-100 px-4 py-3 text-sm font-bold text-gray-700"><input type="radio" name="entry_type" value="Credit" :checked="entry.entry_type === 'Credit'"> Credit [Cr]</label></div></div><div><label class="ledger-label">Amount (PKR) *</label><input type="number" name="amount" min="0" step="0.01" required placeholder="0.00" class="ledger-field" :value="entry.amount ?? ''"></div><div><label class="ledger-label">Payment Method / Bank Account</label><select name="payment_method" class="ledger-field" x-init="$el.value = entry.payment_method ?? $el.options[0].value"><option>Bank A</option><option>Bank B</option><option>Cash Drawer</option><option>Credit Note</option></select></div><div class="md:col-span-2"><label class="ledger-label">Bank Reference / Cheque No.</label><input name="bank_reference" placeholder="CHQ-4412" class="ledger-field" :value="entry.bank_reference ?? ''"></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Section 3: Stock Linkage &amp; Documentation</h3><div class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="ledger-label">Linked Invoice / Trip ID</label><input name="linked_invoice_trip" placeholder="INV-8892 or TR-2026-09-001" class="ledger-field" :value="entry.linked_invoice_trip ?? ''"></div><div><label class="ledger-label">Upload Invoice / Receipt Copy</label><input type="file" name="document" accept="image/png,application/pdf" class="ledger-field"></div><div class="md:col-span-2"><label class="ledger-label">Detailed Remarks / Description</label><textarea x-init="$el.value = entry.remarks ?? ''" name="remarks" rows="4" placeholder="Explain this ledger entry for audit review." class="ledger-field"></textarea></div></div></section>
<div class="flex justify-end gap-2"><a href="{{ route('ledgers.index') }}" class="rounded-lg bg-slate-100 px-5 py-2.5 text-sm font-bold text-slate-600">Cancel</a><button class="rounded-lg bg-gray-700 px-5 py-2.5 text-sm font-bold text-white">Save Ledger Entry</button></div>
</form><style>.ledger-label{display:block;margin-bottom:.3rem;font-size:.75rem;font-weight:700;color:#475569}.ledger-field{width:100%;border:1px solid #cbd5e1;border-radius:.5rem;background:#fff;padding:.65rem .75rem;font-size:.875rem}</style>
@endsection
