@extends('layouts.app')
@php $pageTitle = 'Ledger Detail'; @endphp

@section('content')
<div class="mb-5 flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('ledgers.index') }}" class="text-sm font-bold text-blue-600">&larr; Back to Ledgers</a><h2 class="mt-2 text-2xl font-black text-slate-900">Ledger Voucher Detail</h2><p class="mt-1 text-sm text-slate-500">Complete audit record for {{ $entry['entity'] ?? $entry['entity_name'] }}</p></div><span class="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{{ $entry['verification_status'] ?? 'Pending Verification' }}</span></div>
<div class="space-y-5"><section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Voucher Header &amp; Balance</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-4"><div><p class="ledger-caption">Entity Name</p><p class="ledger-value">{{ $entry['entity'] ?? $entry['entity_name'] }}</p></div><div><p class="ledger-caption">Voucher ID</p><p class="ledger-value">{{ $entry['reference'] ?? $entry['voucher_reference'] }}</p></div><div><p class="ledger-caption">Date</p><p class="ledger-value">{{ $entry['date'] ?? $entry['entry_date'] }}</p></div><div><p class="ledger-caption">Entry Type</p><p class="ledger-value">{{ $entry['type'] ?? $entry['entry_type'] }}</p></div><div><p class="ledger-caption">Previous Balance</p><p class="ledger-value">{{ pkr($entry['previous_balance'] ?? 0) }}</p></div><div><p class="ledger-caption">Transaction Amount</p><p class="ledger-value">{{ pkr($entry['amount'] ?? ($entry['debit'] ?: $entry['credit'])) }}</p></div><div><p class="ledger-caption">Updated Running Balance</p><p class="ledger-value text-blue-700">{{ pkr($entry['running_balance'] ?? $entry['balance']) }}</p></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="mb-5 text-lg font-black text-slate-900">Line-Item SKU Breakdown</h3>@if(count($entry['sku_items'] ?? []) > 0)<div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-400"><th class="px-4 py-3">Item / Brand Name</th><th class="px-4 py-3">Cartons / Units Received</th><th class="px-4 py-3 text-right">Unit Rate (PKR)</th><th class="px-4 py-3 text-right">Total Value (PKR)</th></tr></thead><tbody>@foreach($entry['sku_items'] as $item)<tr class="border-t border-slate-100"><td class="px-4 py-3 font-semibold">{{ $item['name'] }}</td><td class="px-4 py-3">{{ $item['units'] }}</td><td class="px-4 py-3 text-right">{{ pkr($item['rate']) }}</td><td class="px-4 py-3 text-right font-bold">{{ pkr($item['total']) }}</td></tr>@endforeach</tbody></table></div>@else<div class="rounded-lg bg-slate-50 p-5 text-sm text-slate-500">No SKU breakdown applies to this ledger transaction.</div>@endif</section>
<section class="rounded-2xl border border-slate-200 bg-slate-50 p-6"><h3 class="text-lg font-black text-slate-900">Financial &amp; Audit Information</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-4"><div><p class="ledger-caption">Payment Source</p><p class="ledger-value">{{ $entry['payment_method'] ?? 'Not specified' }}</p></div><div><p class="ledger-caption">Reference No.</p><p class="ledger-value">{{ $entry['bank_reference'] ?? 'Not provided' }}</p></div><div><p class="ledger-caption">Attached Document</p><p class="ledger-value">{{ $entry['document_path'] ?? 'No document attached' }}</p></div><div><p class="ledger-caption">Created By</p><p class="ledger-value">{{ $entry['created_by'] ?? 'Admin' }}</p></div><div><p class="ledger-caption">Date &amp; Time Stamp</p><p class="ledger-value">{{ $entry['date'] ?? $entry['entry_date'] }}</p></div><div><p class="ledger-caption">Verification Status</p><p class="ledger-value">{{ $entry['verification_status'] ?? 'Pending Verification' }}</p></div><div class="md:col-span-2"><p class="ledger-caption">Remarks / Description</p><p class="ledger-value">{{ $entry['description'] ?? $entry['remarks'] ?? 'No remarks recorded.' }}</p></div></div></section></div><style>.ledger-caption{font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#94a3b8}.ledger-value{margin-top:.25rem;font-weight:700;color:#1e293b}</style>
@endsection
