@extends('layouts.app')
@php $pageTitle = $claim['return_ref']; @endphp

@section('content')
<div class="mb-5 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('returns.index') }}" class="text-sm font-bold text-blue-600">&larr; Back to Return Claims</a><h2 class="mt-2 text-2xl font-black text-slate-900">{{ $claim['return_ref'] }}</h2><p class="mt-1 text-sm text-slate-500">Return claim detail slip</p></div><x-status-badge :status="$claim['status']" /></div>
<div class="space-y-5">
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">A. Return Header &amp; Audit Info</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-3">@foreach([['Return Reference',$claim['return_ref']],['Date &amp; Time',$claim['date']],['Trip / Invoice Reference',$claim['trip_display'].' / '.$claim['invoice_ref']],['Shopkeeper / Market',$claim['shop'].' ('.$claim['market'].')'],['Deliveryman / Salesman',$claim['deliveryman']],['Distributor',$claim['distributor']]] as [$label,$value])<div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{!! $label !!}</p><p class="mt-1 font-bold text-slate-800">{{ $value }}</p></div>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="mb-5 text-lg font-black text-slate-900">B. SKU-Wise Returned Items Breakdown</h3><div class="overflow-x-auto"><table class="w-full min-w-[52rem] text-sm"><thead><tr class="border-b border-slate-100 text-left text-xs font-bold uppercase tracking-wide text-slate-400"><th class="pb-3">SKU / Item Name</th><th class="pb-3">Batch No. / Expiry</th><th class="pb-3">Returned Qty</th><th class="pb-3 text-right">Unit Rate (PKR)</th><th class="pb-3 text-right">Line Total Value (PKR)</th><th class="pb-3">Primary Return Reason</th></tr></thead><tbody>@foreach($claim['items'] as $item)<tr class="border-b border-slate-50"><td class="py-3 font-semibold">{{ $item['sku'] }}</td><td class="py-3 font-mono text-xs">{{ $item['batch'] }}</td><td class="py-3">{{ $item['quantity'] }}</td><td class="py-3 text-right">{{ pkr($item['rate']) }}</td><td class="py-3 text-right font-bold">{{ pkr($item['line_total']) }}</td><td class="py-3">{{ $item['reason'] }}</td></tr>@endforeach</tbody></table></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="mb-5 text-lg font-black text-slate-900">C. Reason &amp; Classification Analysis</h3><div class="grid grid-cols-1 gap-5 text-sm md:grid-cols-3"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Main Reason Category</p><p class="mt-1 font-bold text-slate-800">{{ $claim['main_reason'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Physical Condition</p><p class="mt-1 font-bold text-slate-800">{{ $claim['condition'] }}</p></div><div class="md:col-span-3"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Detailed Remarks / Notes</p><p class="mt-1 text-slate-700">{{ $claim['remarks'] }}</p></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-slate-50 p-6"><h3 class="mb-5 text-lg font-black text-slate-900">D. Financial &amp; Settlement Status</h3><div class="grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-4"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Gross Returned Amount</p><p class="mt-1 text-lg font-black text-red-600">{{ pkr($claim['value']) }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Adjusted Against Invoice / Credit Note No</p><p class="mt-1 font-bold text-slate-800">{{ $claim['credit_note'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Impact on Salesman Cash</p><p class="mt-1 font-bold text-slate-800">{{ $claim['impact'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Distributor Claim Status</p><p class="mt-1 font-bold text-slate-800">{{ $claim['claim_status'] }}</p></div></div></section>
</div>
@endsection
