@extends('layouts.app')
@php $pageTitle = 'Add Expense'; @endphp

@section('content')
<div x-data="{ categories: ['Fuel', 'Repair/Maintenance', 'Driver Meals/Allowance', 'Warehouse/Office Rent', 'Utilities', 'Loading/Unloading Charges', 'Marketing/Misc'], newCategory: '', addCategory() { const value = this.newCategory.trim(); if (value && !this.categories.includes(value)) { this.categories.push(value); this.newCategory = ''; } } }">
    <div class="mb-5 flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('expenses.index') }}" class="text-sm font-bold text-gray-700">&larr; Back to Expenses</a><h2 class="mt-2 text-2xl font-black text-slate-900">New Expense</h2><p class="mt-1 text-sm text-slate-500">Record an expense and optionally link it to a trip.</p></div><span class="rounded-full bg-gray-100 px-3 py-1.5 text-xs font-bold text-gray-700">Draft Entry</span></div>
    <div class="grid grid-cols-1 gap-5 xl:grid-cols-3">
        <form class="space-y-5 xl:col-span-2" method="POST" action="{{ route('expenses.store') }}" enctype="multipart/form-data">@csrf
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="mb-5 text-lg font-black text-slate-900">Group A: Basic Info</h3><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="expense-label">Expense Date *</label><input type="date" required class="expense-field" name="date"></div><div><label class="expense-label">Category *</label><select required class="expense-field" name="category"><template x-for="category in categories" :key="category"><option x-text="category"></option></template></select></div><div class="md:col-span-2"><label class="expense-label">Sub-Category / Description</label><input placeholder="e.g., Diesel for Suzuki Bolan" class="expense-field" name="notes"></div></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="mb-5 text-lg font-black text-slate-900">Group B: Financials &amp; Payment Method</h3><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="expense-label">Amount (PKR) *</label><input type="number" min="0" step="0.01" required placeholder="0.00" class="expense-field" name="amount"></div><div><label class="expense-label">Paid Via *</label><select required class="expense-field" name="source"><option>Cash in Hand</option><option>Bank Account</option><option>Driver Petty Cash</option></select></div><div><label class="expense-label">Bank / Account Name</label><select class="expense-field" name="payment_source"><option>Bank A</option><option>Bank B</option><option>Not Applicable</option></select></div><div><label class="expense-label">Receipt / Slip Attachment</label><input type="file" class="expense-field" name="attachment"></div><div class="md:col-span-2"><label class="expense-label">Receipt / Voucher No</label><input placeholder="e.g., Fuel Slip #4412" class="expense-field" name="voucher"></div></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="mb-5 text-lg font-black text-slate-900">Group C: Operational Linking (Trip &amp; Vehicle)</h3><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="expense-label">Link to Trip / Route ID</label><select class="expense-field" name="trip_id"><option value="">Not linked</option>@foreach($trips as $trip)<option value="{{ $trip->id }}">{{ $trip->trip_number }} ? {{ $trip->deliveryman_name }}</option>@endforeach</select></div><div><label class="expense-label">Link to Driver / Deliveryman</label><select class="expense-field" name="driver"><option>Not linked</option><option>Ahmed Khan</option><option>Bilal Raza</option><option>Usman Tariq</option></select></div><div><label class="expense-label">Vehicle / Van Number</label><select class="expense-field" name="route"><option>Not linked</option><option>KHI-1234</option><option>KHI-4567</option><option>KHI-7890</option></select></div></div></section>
            <div class="flex justify-end gap-2"><a href="{{ route('expenses.index') }}" class="rounded-lg bg-slate-100 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</a><button type="submit" class="rounded-lg bg-gray-800 px-5 py-2.5 text-sm font-bold text-white">Save Expense</button></div>
        </form>
        <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-start justify-between gap-3"><div><h3 class="text-lg font-black text-slate-900">Expense Categories</h3><p class="mt-1 text-xs text-slate-500">Add a category to use for this expense.</p></div><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-500" x-text="categories.length"></span></div><form class="mt-5 flex gap-2" @submit.prevent="addCategory()"><input x-model="newCategory" required placeholder="e.g., Internet Charges" class="expense-field"><button class="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">Add</button></form><div class="mt-5 space-y-2"><template x-for="category in categories" :key="category"><div class="flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-700"><span x-text="category"></span><span class="text-xs text-gray-700">Available</span></div></template></div><div class="mt-5 rounded-lg bg-gray-100 p-3 text-xs leading-5 text-gray-700">Add a category above, then select it from the Category field in Group A. The selected category is saved with the expense.</div></aside>
    </div>
</div>
<style>[x-cloak]{display:none!important}.expense-label{display:block;margin-bottom:.25rem;font-size:.75rem;font-weight:700;color:#475569}.expense-field{width:100%;border:1px solid #cbd5e1;border-radius:.5rem;background:#fff;padding:.625rem .75rem;font-size:.875rem}</style>
@endsection
