@extends('layouts.app')
@php $pageTitle = 'Expenses'; @endphp

@section('content')
<div x-data="{ addOpen: false, categoryOpen: false, newCategory: '', categories: ['Fuel', 'Repair/Maintenance', 'Driver Meals/Allowance', 'Warehouse/Office Rent', 'Utilities', 'Loading/Unloading Charges', 'Marketing/Misc'], addCategory() { const value = this.newCategory.trim(); if (value && !this.categories.includes(value)) { this.categories.push(value); this.newCategory = ''; this.categoryOpen = false; } } }" @keydown.escape.window="addOpen = false; categoryOpen = false">
    <div class="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-orange-600">AAA Traders</p><h2 class="mt-1 text-2xl font-black text-slate-900">Expenses</h2><p class="mt-1 text-sm text-slate-500">Daily trip costs, office expenses, and payment verification.</p></div><a href="{{ route('expenses.create') }}" class="rounded-lg bg-orange-500 px-4 py-2.5 text-sm font-bold text-white">+ Add Expense</a></div>

    <div class="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Total Expenses Today',$todayTotal,'#c2410c','#fff7ed'],['Total Monthly Fuel & Maintenance',$monthlyFuelMaintenance,'#0369a1','#f0f9ff'],['Total Staff Salaries & Allowances',$staffTotal,'#7c3aed','#f5f3ff'],['Total Pending Approvals / Unverified',$pendingTotal,'#b45309','#fffbeb']] as [$label,$value,$color,$background])
        <div class="min-h-32 rounded-xl border border-slate-200 p-5 shadow-sm" style="background:{{ $background }}"><p class="text-xs font-bold uppercase tracking-wide" style="color:{{ $color }};opacity:.75">{{ $label }}</p><p class="mt-2 text-2xl font-black" style="color:{{ $color }}">{{ pkr($value) }}</p></div>
        @endforeach
    </div>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-6 py-5"><h3 class="text-lg font-black text-slate-900">Expenses Main Table</h3><p class="mt-1 text-xs text-slate-500">Every daily trip and general office expense in one audit-friendly log.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[78rem] text-sm"><thead><tr class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-400"><th class="px-5 py-3">Expense ID</th><th class="px-5 py-3">Date</th><th class="px-5 py-3">Expense Category</th><th class="px-5 py-3">Payer / Source</th><th class="px-5 py-3">Driver / Staff Name</th><th class="px-5 py-3">Route / Vehicle No</th><th class="px-5 py-3 text-right">Amount (PKR)</th><th class="px-5 py-3">Receipt / Voucher No</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($expenses as $expense)<tr class="hover:bg-slate-50"><td class="px-5 py-4 font-mono text-xs font-black text-blue-700">{{ $expense['expense_id'] }}</td><td class="px-5 py-4 whitespace-nowrap">{{ $expense['date'] }}</td><td class="px-5 py-4 font-semibold">{{ $expense['category'] }}</td><td class="px-5 py-4 text-slate-600">{{ $expense['source'] }}</td><td class="px-5 py-4">{{ $expense['driver'] }}</td><td class="px-5 py-4 text-slate-600">{{ $expense['route'] }}</td><td class="px-5 py-4 text-right font-black">{{ pkr($expense['amount']) }}</td><td class="px-5 py-4 font-mono text-xs">{{ $expense['voucher'] }}</td><td class="px-5 py-4"><x-status-badge :status="$expense['status']" /></td><td class="px-5 py-4"><a href="{{ route('expenses.show', $expense['id']) }}" class="whitespace-nowrap rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700 hover:bg-blue-100">View Details</a></td></tr>@endforeach</tbody></table></div></section>

    <div x-show="addOpen" x-cloak x-transition class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4" @click.self="addOpen = false"><div class="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" @click.stop><div class="flex items-center justify-between border-b border-slate-100 pb-4"><div><h3 class="text-xl font-black text-slate-900">Add Expense</h3><p class="mt-1 text-xs text-slate-500">Record a trip, vehicle, staff, or office expense.</p></div><button type="button" @click="addOpen = false" class="text-2xl text-slate-400">&times;</button></div><form class="mt-5 space-y-6" @submit.prevent="addOpen = false">
        <section><h4 class="mb-3 text-sm font-black text-slate-800">Group A: Basic Info</h4><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="expense-label">Expense Date *</label><input type="date" required class="expense-field"></div><div><label class="expense-label">Category *</label><select required class="expense-field"><template x-for="category in categories" :key="category"><option x-text="category"></option></template></select></div><div class="md:col-span-2"><label class="expense-label">Sub-Category / Description</label><input placeholder="e.g., Diesel for Suzuki Bolan" class="expense-field"></div></div></section>
        <section><h4 class="mb-3 text-sm font-black text-slate-800">Group B: Financials &amp; Payment Method</h4><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="expense-label">Amount (PKR) *</label><input type="number" min="0" step="0.01" required placeholder="0.00" class="expense-field"></div><div><label class="expense-label">Paid Via *</label><select required class="expense-field"><option>Cash in Hand</option><option>Bank Account</option><option>Driver Petty Cash</option></select></div><div><label class="expense-label">Bank / Account Name</label><select class="expense-field"><option>Bank A</option><option>Bank B</option><option>Not Applicable</option></select></div><div><label class="expense-label">Receipt / Slip Attachment</label><input type="file" class="expense-field"></div><div class="md:col-span-2"><label class="expense-label">Receipt / Voucher No</label><input placeholder="e.g., Fuel Slip #4412" class="expense-field"></div></div></section>
        <section><h4 class="mb-3 text-sm font-black text-slate-800">Group C: Operational Linking (Trip &amp; Vehicle)</h4><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label class="expense-label">Link to Trip / Route ID</label><select class="expense-field"><option>Not linked</option><option>TR-2026-09-001</option><option>TR-2026-09-002</option></select></div><div><label class="expense-label">Link to Driver / Deliveryman</label><select class="expense-field"><option>Not linked</option><option>Ahmed Khan</option><option>Bilal Raza</option><option>Usman Tariq</option></select></div><div><label class="expense-label">Vehicle / Van Number</label><select class="expense-field"><option>Not linked</option><option>KHI-1234</option><option>KHI-4567</option><option>KHI-7890</option></select></div></div></section>
        <div class="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" @click="addOpen = false" class="rounded-lg bg-slate-100 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</button><button class="rounded-lg bg-orange-500 px-5 py-2.5 text-sm font-bold text-white">Save Expense</button></div>
    </form></div></div>
    </form></div></div>
</div>

<div x-show="categoryOpen" x-cloak x-transition class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4" @click.self="categoryOpen = false"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl" @click.stop><div class="flex items-center justify-between"><div><h3 class="text-lg font-black text-slate-900">Expense Categories</h3><p class="mt-1 text-xs text-slate-500">Add categories for this client view.</p></div><button type="button" @click="categoryOpen = false" class="text-2xl text-slate-400">&times;</button></div><div class="mt-5 space-y-2"><template x-for="category in categories" :key="category"><div class="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-700" x-text="category"></div></template></div><form class="mt-5 flex gap-2" @submit.prevent="addCategory()"><input x-model="newCategory" required placeholder="New category name" class="expense-field"><button class="rounded-lg bg-orange-500 px-4 py-2 text-sm font-bold text-white">Add</button></form></div></div>
<style>[x-cloak]{display:none!important}.expense-label{display:block;margin-bottom:.25rem;font-size:.75rem;font-weight:700;color:#475569}.expense-field{width:100%;border:1px solid #cbd5e1;border-radius:.5rem;background:#fff;padding:.625rem .75rem;font-size:.875rem}</style>
@endsection
