@extends('layouts.app')
@php $pageTitle = 'Expenses'; @endphp

@section('content')
<div x-data="{ addOpen: false, categoryOpen: false, newCategory: '', categories: ['Fuel', 'Repair/Maintenance', 'Driver Meals/Allowance', 'Warehouse/Office Rent', 'Utilities', 'Loading/Unloading Charges', 'Marketing/Misc'], addCategory() { const value = this.newCategory.trim(); if (value && !this.categories.includes(value)) { this.categories.push(value); this.newCategory = ''; this.categoryOpen = false; } } }" @keydown.escape.window="addOpen = false; categoryOpen = false">
    <div class="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-gray-700">AAA Traders</p><h2 class="mt-1 text-2xl font-black text-slate-900">Expenses</h2><p class="mt-1 text-sm text-slate-500">Daily trip costs, office expenses, and payment verification.</p></div><a href="{{ route('expenses.create') }}" class="rounded-lg bg-gray-800 px-4 py-2.5 text-sm font-bold text-white">+ Add Expense</a></div>

    <div class="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Total Expenses Today',$todayTotal,'#333333','#efefef'],['Total Monthly Fuel & Maintenance',$monthlyFuelMaintenance,'#222222','#f0f0f0'],['Total Staff Salaries & Allowances',$staffTotal,'#444444','#f0f0f0'],['Total Pending Approvals / Unverified',$pendingTotal,'#444444','#ececec']] as [$label,$value,$color,$background])
        <div class="min-h-32 rounded-xl border border-slate-200 p-5 shadow-sm" style="background:{{ $background }}"><p class="text-xs font-bold uppercase tracking-wide" style="color:{{ $color }};opacity:.75">{{ $label }}</p><p class="mt-2 text-2xl font-black" style="color:{{ $color }}">{{ pkr($value) }}</p></div>
        @endforeach
    </div>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-6 py-5"><h3 class="text-lg font-black text-slate-900">Expenses Main Table</h3><p class="mt-1 text-xs text-slate-500">Every daily trip and general office expense in one audit-friendly log.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[78rem] text-sm"><thead><tr class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-400"><th class="px-5 py-3">Expense ID</th><th class="px-5 py-3">Date</th><th class="px-5 py-3">Expense Category</th><th class="px-5 py-3">Payer / Source</th><th class="px-5 py-3">Driver / Staff Name</th><th class="px-5 py-3">Route / Vehicle No</th><th class="px-5 py-3 text-right">Amount (PKR)</th><th class="px-5 py-3">Receipt / Voucher No</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($expenses as $expense)<tr class="hover:bg-slate-50"><td class="px-5 py-4 font-mono text-xs font-black text-gray-700">{{ $expense['expense_id'] }}</td><td class="px-5 py-4 whitespace-nowrap">{{ $expense['date'] }}</td><td class="px-5 py-4 font-semibold">{{ $expense['category'] }}</td><td class="px-5 py-4 text-slate-600">{{ $expense['source'] }}</td><td class="px-5 py-4">{{ $expense['driver'] }}</td><td class="px-5 py-4 text-slate-600">{{ $expense['route'] }}</td><td class="px-5 py-4 text-right font-black">{{ pkr($expense['amount']) }}</td><td class="px-5 py-4 font-mono text-xs">{{ $expense['voucher'] }}</td><td class="px-5 py-4"><x-status-badge :status="$expense['status']" /></td><td class="px-5 py-4"><a href="{{ route('expenses.show', $expense['id']) }}" class="whitespace-nowrap rounded-lg bg-gray-100 px-3 py-2 text-xs font-bold text-gray-700 hover:bg-gray-100">View Details</a></td></tr>@endforeach</tbody></table></div></section>

</div>
@endsection
