@extends('layouts.app')
@php $pageTitle = $record['expense_id']; @endphp

@section('content')
<div class="mb-5 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('expenses.index') }}" class="text-sm font-bold text-blue-600">&larr; Back to Expenses</a><h2 class="mt-2 text-2xl font-black text-slate-900">Expense Voucher</h2><p class="mt-1 text-sm text-slate-500">{{ $record['expense_id'] }} · Audit-ready expense detail</p></div><x-status-badge :status="$record['status']" /></div>
<div class="space-y-5">
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Voucher Header</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-2 lg:grid-cols-4">@foreach([['Expense ID',$record['expense_id']],['Date',$record['date']],['Status',$record['status']],['Approved By',$record['approved_by']]] as [$label,$value])<div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-1 font-bold text-slate-800">{{ $value }}</p></div>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Payment Breakdown</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-3"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Amount</p><p class="mt-1 text-xl font-black text-orange-600">{{ pkr($record['amount']) }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Payment Source</p><p class="mt-1 font-bold text-slate-800">{{ $record['payment_source'] }} · {{ $record['source'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Receipt Number</p><p class="mt-1 font-bold text-slate-800">{{ $record['receipt'] }}</p></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="text-lg font-black text-slate-900">Operational Context</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-3"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Linked Driver Name</p><p class="mt-1 font-bold text-slate-800">{{ $record['driver'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Vehicle Number</p><p class="mt-1 font-bold text-slate-800">{{ $record['route'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Market / Route Covered</p><p class="mt-1 font-bold text-slate-800">{{ $record['market'] }}</p></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-slate-50 p-6"><h3 class="text-lg font-black text-slate-900">Audit Trail</h3><div class="mt-5 grid grid-cols-1 gap-5 text-sm md:grid-cols-3"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Created By</p><p class="mt-1 font-bold text-slate-800">{{ $record['created_by'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Created Date / Time</p><p class="mt-1 font-bold text-slate-800">{{ $record['created_at'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Remarks / Notes</p><p class="mt-1 text-slate-700">{{ $record['notes'] }}</p></div></div></section>
</div>
@endsection
